name: adminpannal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  cached_network_image: ^3.3.1
  eva_icons_flutter: ^3.0.2

  file_picker: ^8.0.1
  image_picker: ^1.1.2

  get: ^4.3.8
  provider: ^6.1.2

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.5
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  flutter_native_splash: 2.2.0+1
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^0.23.0+1
  intl: ^0.19.0
  lottie: ^3.1.2
  onesignal_flutter: ^5.1.5
  page_transition: ^2.1.0
  percent_indicator: ^3.4.0
  phlox_animations: ^2.1.1
  photo_view: ^0.15.0
  rive: ^0.13.9
  shared_preferences: ^2.3.0
  path: ^1.9.0
  flutter_colorpicker: ^1.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.8.0
  simple_star_rating: ^0.0.3
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#1f1d2c"
  image: assets/images/KSK Logo.png
  android_12:
    image: assets/images/KSK Logo.png
    color: "#1f1d2c"


flutter:
  uses-material-design: true

  assets:
    - assets/images/