// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANZqCB7zS8ReRRDI7oeJRAr4Z9a5Pa1OU',
    appId: '1:1063108267034:web:89645ed1a82d865645d5a3',
    messagingSenderId: '1063108267034',
    projectId: 'krishisevakendra-8430a',
    authDomain: 'krishisevakendra-8430a.firebaseapp.com',
    storageBucket: 'krishisevakendra-8430a.appspot.com',
    measurementId: 'G-P1XHWDLBE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlqg0XfRUj88bxGyBY_eCQcDBhMdv9s9w',
    appId: '1:1063108267034:android:caf314f5c5184c1b45d5a3',
    messagingSenderId: '1063108267034',
    projectId: 'krishisevakendra-8430a',
    storageBucket: 'krishisevakendra-8430a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8kps1hk1IemmfscfNh4f903Ns2GhPjTE',
    appId: '1:1063108267034:ios:959ef8896527c73145d5a3',
    messagingSenderId: '1063108267034',
    projectId: 'krishisevakendra-8430a',
    storageBucket: 'krishisevakendra-8430a.appspot.com',
    iosBundleId: 'com.example.adminpannal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8kps1hk1IemmfscfNh4f903Ns2GhPjTE',
    appId: '1:1063108267034:ios:959ef8896527c73145d5a3',
    messagingSenderId: '1063108267034',
    projectId: 'krishisevakendra-8430a',
    storageBucket: 'krishisevakendra-8430a.appspot.com',
    iosBundleId: 'com.example.adminpannal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANZqCB7zS8ReRRDI7oeJRAr4Z9a5Pa1OU',
    appId: '1:1063108267034:web:f94e1af5cd62dbd845d5a3',
    messagingSenderId: '1063108267034',
    projectId: 'krishisevakendra-8430a',
    authDomain: 'krishisevakendra-8430a.firebaseapp.com',
    storageBucket: 'krishisevakendra-8430a.appspot.com',
    measurementId: 'G-NNDGHCXVG8',
  );
}
